# Generated by Django 5.2.4 on 2025-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('review_text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('submited_at', models.DateTimeField(auto_now=True, verbose_name='Дата прихода отзыва')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации отзыва')),
                ('status', models.CharField(choices=[('pending', 'на рассмотрении'), ('published', 'Опубликованно')], default='pending', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='ThankYouLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thank_you_letters/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
