# Generated by Django 5.2.4 on 2025-08-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreview',
            options={'verbose_name': 'Отзыв клиента', 'verbose_name_plural': 'Отзывы клиента'},
        ),
        migrations.AlterModelOptions(
            name='thankyouletter',
            options={'verbose_name': 'Благодарственное письмо', 'verbose_name_plural': 'Благодарственные письма'},
        ),
    ]
