# Generated by Django 5.2.4 on 2025-08-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customerreview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='submited_at',
            new_name='submitted_at',
        ),
    ]
